version: "3.2"

services:
  api:
    image: backend:1.0.0
    container_name: ${SERVER_HOST}
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - ./backend:/usr/app
      - server-v-node-modules:/backend/node_modules
    depends_on:
      - db
  db:
    image: db:1.0.0
    container_name: ${DATABASE_HOST}
    build:
      context: ./database
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    volumes:
      - database-v:/data/db

volumes:
  server-v-node-modules:
    name: "server-v-node-modules"
  database-v:
    name: "database-v"